C_USERNAME = "C_USERNAME"
C_PASSWORD = "C_PASSWORD"
C_NAME = "C_NAME"
C_MAILADDR = "C_MAILADDR"
C_PRIVILEGE = "C_PRIVILEGE"
C_ERROR_MSG = "C_ERROR_MSG"

IS_LOGED_IN = "IS_LOGED_IN"
IS_MANAGER = "IS_MANAGER" 